package dev.gajaba.anticheat.checks;

public enum CheckType {
    AURA_A, AURA_B, AURA_C, AURA_D,
    AURA_E, AURA_F,
    AUTOCLICKER_A, AUTOCLICKER_B, AUTOCLICKER_C,
    AUTOCLICKER_D, AUTOCLICKER_E,
    AUTOBLOCK_A, CRITICALS_A,
    REACH_A, REACH_B, REACH_C,
    VELOCITY_A, VELOCITY_B, VELOCITY_C,
    FLY_B, FLY_C, FLY_D, FLY_E,
    SPEED_B, SPEED_C, SPEED_D,
    NOFALL_A, NOFALL_B,
    PHASE_A, PHASE_B,
    NOSLOW_A, NOSLOW_B,
    JESUS_A, SPIDER_A, STEP_A,
    BUNNYHOP_A, CROUCH_A, PREDICT_A,
    HONEYPOT_A,
    BADPACKETS_A, BADPACKETS_B, BADPACKETS_C,
    PINGSPOOF_A, BLINK_A,
    FASTPLACE_A, INVMOVE_A
}
